name: Listar permisos roles

on:
  workflow_dispatch:
    inputs:
      role_name: 
        description: "Nombre del role"
        required: false
        default: "NN"

env:
  PROJECT: ${{ github.event.repository.name }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  list-policies:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: Configurando credenciales para AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Politicas
        run: |
         aws iam list-attached-role-policies --role-name "${{ github.event.inputs.role_name }}" --output table